apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: games.karcade.io
spec:
  group: karcade.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                romPath:
                  type: string
  scope: Namespaced
  names:
    plural: "games"
    singular: "game"
    kind: Game
    shortNames:
      - ga
      - g